quartz:
  enabled: true
server:
  port: 8081
  servlet:
    context-path: /

# 项目配置
spring:
  application:
    name: stock-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# 两个spring 中间用 --- 区别开来
---
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root123
#    url: jdbc:mysql://47.99.64.37:3306/quartz?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://127.0.0.1:3306/quartz?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间(毫秒)
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置有一个连接在连接池中的最小生存时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql将无法统计，'wall'用于防火墙
    filters: stat, wall
    # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

---
mybatis-plus:
  mapper-locations: classpath:mapper/**.xml
  global-config:
    sql-parser-cache: true
    # sql打印
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.xnpool.scheduler.common.redis.lock: debug
    com.xnpool.scheduler.stock: debug

# redis
spring:
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3000
    jedis:
      pool:
        max-active: 100
        max-wait: 1500
        max-idle: 10
        min-idle: 0



#redis集群
#spring:
#    redis:
#        cluster:
#            nodes:
#                - 10.5.1.105:6379
#                - 10.5.1.105:6380
#                - 10.5.1.105:6381
#                - 10.5.1.105:6479
#                - 10.5.1.105:6480
#                - 10.5.1.105:6481
#            max-redirects: 5
#        #密码密文
#        #password: n/0YQh0A9JykCQctl2jPzEO0qg///HAP/mja7UPonbCXE0luawXDoUdqaw9bzzEM++14KOFs91wKYjEjGGAlaA==
#        #密码明文
#        #password: 123456
#        #无需密码
#        password:
#        pool:
#            max-active: 100
#            max-wait: 6000
#            max-idle: 200
#            min-idle: 100
#        timeout: 6000

# 自定义参数
param:
  increase: 1      #涨幅
  transNum: 1000   #成交数量
  stockUrl0: http://push2.eastmoney.com/api/qt/stock/get?ut=fa5fd1943c7b386f172d6893dbfba10b&invt=2&fltt=2&fields=f43,f57,f58,f169,f170,f46,f44,f51,f168,f47,f164,f163,f116,f60,f45,f52,f50,f48,f167,f117,f71,f161,f49,f530,f135,f136,f137,f138,f139,f141,f142,f144,f145,f147,f148,f140,f143,f146,f149,f55,f62,f162,f92,f173,f104,f105,f84,f85,f183,f184,f185,f186,f187,f188,f189,f190,f191,f192,f107,f111,f86,f177,f78,f110,f262,f263,f264,f267,f268,f250,f251,f252,f253,f254,f255,f256,f257,f258,f266,f269,f270,f271,f273,f274,f275,f127,f199,f128,f193,f196,f194,f195,f197,f80,f280,f281,f282,f284,f285,f286,f287&secid=0.@code&cb=jQuery1124014653070091256182_@time&_=@time
  stockUrl6: http://push2.eastmoney.com/api/qt/stock/get?ut=fa5fd1943c7b386f172d6893dbfba10b&invt=2&fltt=2&fields=f43,f57,f58,f169,f170,f46,f44,f51,f168,f47,f164,f163,f116,f60,f45,f52,f50,f48,f167,f117,f71,f161,f49,f530,f135,f136,f137,f138,f139,f141,f142,f144,f145,f147,f148,f140,f143,f146,f149,f55,f62,f162,f92,f173,f104,f105,f84,f85,f183,f184,f185,f186,f187,f188,f189,f190,f191,f192,f107,f111,f86,f177,f78,f110,f262,f263,f264,f267,f268,f250,f251,f252,f253,f254,f255,f256,f257,f258,f266,f269,f270,f271,f273,f274,f275,f127,f199,f128,f193,f196,f194,f195,f197,f80,f280,f281,f282,f284,f285,f286,f287&secid=1.@code&cb=jQuery1124014653070091256182_@time&_=@time
  #券商业绩月报
  brokerAchievementUrl: http://dcfm.eastmoney.com/em_mutisvcexpandinterface/api/js/get?type=QSYJBG_MReport&token=70f12f2f4f091e459a279469fe49eca5&st=RQ&sr=-1&p=1&ps=1000&js=var%20sZoUQVXE={pages:(tp),data:(x)}&filter=(RQ=%27@time%27)&rt=53097309
  #异动  time=1592832363671 code=601766  date=20200622
  diffChangeUrl: http://push2ex.eastmoney.com/getStockChanges?cb=jQuery1124032763203312113376_@time&code=@code&market=1&date=@date&ut=7eea3edcaed734bea9cbfc24409ed989&dpt=wzchanges&_=@time
  industryCapitalUrl: http://push2.eastmoney.com/api/qt/clist/get?pn=1&pz=62&po=1&np=1&ut=b2884a393a59ad64002292a3e90d46a5&fltt=2&invt=2&fid=f62&fs=m:90+t:2&stat=1&fields=f12,f14,f2,f3,f62,f184,f66,f69,f72,f75,f78,f81,f84,f87,f204,f205,f124&rt=53106058&cb=jQuery183004060919341948055_1593180332817&_=1593181742690
  val: 张三
  bean:
    id: 20
    name: 张三
  arr1: 1, 3, 4
  arr2: [1, 3, 4]
  list:
    - lista
    - listb
  map:
    a: mapa
    b: mapb
  listmap:
    - a: a
      b: b
      c: c
    - d: d
      e: e
      f: f

---
######freemarker视图配置######
spring:
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .html
    template-loader-path: classpath:/templates/